// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {deps} from '../models';
import {bedrock} from '../models';
import {zen} from '../models';
import {router} from '../models';

export function AddModel(arg1:main.ModelInput):Promise<void>;

export function AddProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClearKey(arg1:string):Promise<void>;

export function Config():Promise<Array<main.ModelInfo>>;

export function DependencyStatus():Promise<Array<deps.Tool>>;

export function DiscoverBedrockModels(arg1:string):Promise<Array<bedrock.Model>>;

export function DiscoverOllamaModels():Promise<Array<main.OllamaModel>>;

export function DiscoverZenModels():Promise<Array<zen.Model>>;

export function EnableRemoteControl(arg1:string):Promise<void>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function ImportProjects(arg1:Array<main.ProjectEntry>):Promise<void>;

export function InstallLitellmRuntime():Promise<void>;

export function InstallPwsh():Promise<void>;

export function KeyStatus():Promise<Array<main.KeyInfo>>;

export function KillSession(arg1:string):Promise<void>;

export function LaunchSession(arg1:string,arg2:string,arg3:boolean):Promise<main.SessionInfo>;

export function ListProjectDocs(arg1:string):Promise<main.DocListing>;

export function ListProjects():Promise<Array<main.ProjectView>>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function ListSessionDocs(arg1:string):Promise<main.DocListing>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function LitellmRuntimeStatus():Promise<router.RuntimeStatus>;

export function Models():Promise<Array<main.ModelDetail>>;

export function OpenProjectDoc(arg1:string,arg2:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PinProject(arg1:string,arg2:boolean):Promise<void>;

export function PlanUsage():Promise<main.PlanUsage>;

export function RemoveModel(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RenderProjectDoc(arg1:string,arg2:string):Promise<main.DocRender>;

export function SelectSession(arg1:string):Promise<void>;

export function SessionStats(arg1:string):Promise<main.SessionStats>;

export function SetKey(arg1:string,arg2:string):Promise<void>;

export function SwapModel(arg1:string,arg2:string):Promise<main.SessionInfo>;

export function WSPort():Promise<number>;

export function WSToken():Promise<string>;
