// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {bedrock} from '../models';

export function AddModel(arg1:main.ModelInput):Promise<void>;

export function ClearKey(arg1:string):Promise<void>;

export function Config():Promise<Array<main.ModelInfo>>;

export function DiscoverBedrockModels(arg1:string):Promise<Array<bedrock.Model>>;

export function EnableRemoteControl(arg1:string):Promise<void>;

export function KeyStatus():Promise<Array<main.KeyInfo>>;

export function KillSession(arg1:string):Promise<void>;

export function LaunchSession(arg1:string,arg2:string,arg3:boolean):Promise<main.SessionInfo>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function Models():Promise<Array<main.ModelDetail>>;

export function PickFolder():Promise<string>;

export function RemoveModel(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SelectSession(arg1:string):Promise<void>;

export function SessionStats(arg1:string):Promise<main.SessionStats>;

export function SetKey(arg1:string,arg2:string):Promise<void>;

export function SwapModel(arg1:string,arg2:string):Promise<main.SessionInfo>;

export function WSPort():Promise<number>;

export function WSToken():Promise<string>;
