// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['main']['App']['AddModel'](arg1);
}

export function ClearKey(arg1) {
  return window['go']['main']['App']['ClearKey'](arg1);
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function DiscoverBedrockModels(arg1) {
  return window['go']['main']['App']['DiscoverBedrockModels'](arg1);
}

export function EnableRemoteControl(arg1) {
  return window['go']['main']['App']['EnableRemoteControl'](arg1);
}

export function KeyStatus() {
  return window['go']['main']['App']['KeyStatus']();
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function LaunchSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchSession'](arg1, arg2, arg3);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PlanUsage() {
  return window['go']['main']['App']['PlanUsage']();
}

export function RemoveModel(arg1) {
  return window['go']['main']['App']['RemoveModel'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SelectSession(arg1) {
  return window['go']['main']['App']['SelectSession'](arg1);
}

export function SessionStats(arg1) {
  return window['go']['main']['App']['SessionStats'](arg1);
}

export function SetKey(arg1, arg2) {
  return window['go']['main']['App']['SetKey'](arg1, arg2);
}

export function SwapModel(arg1, arg2) {
  return window['go']['main']['App']['SwapModel'](arg1, arg2);
}

export function WSPort() {
  return window['go']['main']['App']['WSPort']();
}

export function WSToken() {
  return window['go']['main']['App']['WSToken']();
}
