// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['main']['App']['AddModel'](arg1);
}

export function AddProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProvider'](arg1, arg2, arg3);
}

export function BrowseCompanionPack() {
  return window['go']['main']['App']['BrowseCompanionPack']();
}

export function CancelPackGen() {
  return window['go']['main']['App']['CancelPackGen']();
}

export function ClearCompanionPack() {
  return window['go']['main']['App']['ClearCompanionPack']();
}

export function ClearImagegenKey(arg1) {
  return window['go']['main']['App']['ClearImagegenKey'](arg1);
}

export function ClearKey(arg1) {
  return window['go']['main']['App']['ClearKey'](arg1);
}

export function CompanionState() {
  return window['go']['main']['App']['CompanionState']();
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function DeleteCompanionPack(arg1) {
  return window['go']['main']['App']['DeleteCompanionPack'](arg1);
}

export function DependencyStatus() {
  return window['go']['main']['App']['DependencyStatus']();
}

export function DiscardPackGen() {
  return window['go']['main']['App']['DiscardPackGen']();
}

export function DiscoverBedrockModels(arg1) {
  return window['go']['main']['App']['DiscoverBedrockModels'](arg1);
}

export function DiscoverOllamaModels() {
  return window['go']['main']['App']['DiscoverOllamaModels']();
}

export function DiscoverZenModels() {
  return window['go']['main']['App']['DiscoverZenModels']();
}

export function EnableRemoteControl(arg1) {
  return window['go']['main']['App']['EnableRemoteControl'](arg1);
}

export function ExportCompanionPack() {
  return window['go']['main']['App']['ExportCompanionPack']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetCompanionConfig() {
  return window['go']['main']['App']['GetCompanionConfig']();
}

export function GetCompanionKind() {
  return window['go']['main']['App']['GetCompanionKind']();
}

export function ImportCompanionPack() {
  return window['go']['main']['App']['ImportCompanionPack']();
}

export function ImportProjects(arg1) {
  return window['go']['main']['App']['ImportProjects'](arg1);
}

export function InspectPackGenBase(arg1) {
  return window['go']['main']['App']['InspectPackGenBase'](arg1);
}

export function InstallLitellmRuntime() {
  return window['go']['main']['App']['InstallLitellmRuntime']();
}

export function InstallPwsh() {
  return window['go']['main']['App']['InstallPwsh']();
}

export function KeyStatus() {
  return window['go']['main']['App']['KeyStatus']();
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function LaunchSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchSession'](arg1, arg2, arg3);
}

export function ListCompanionPacks() {
  return window['go']['main']['App']['ListCompanionPacks']();
}

export function ListProjectDocs(arg1) {
  return window['go']['main']['App']['ListProjectDocs'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSessionDocs(arg1) {
  return window['go']['main']['App']['ListSessionDocs'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LitellmRuntimeStatus() {
  return window['go']['main']['App']['LitellmRuntimeStatus']();
}

export function LoadCompanionPack() {
  return window['go']['main']['App']['LoadCompanionPack']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenProjectDoc(arg1, arg2) {
  return window['go']['main']['App']['OpenProjectDoc'](arg1, arg2);
}

export function PackGenConditions() {
  return window['go']['main']['App']['PackGenConditions']();
}

export function PackGenEstimate(arg1, arg2) {
  return window['go']['main']['App']['PackGenEstimate'](arg1, arg2);
}

export function PackGenProviders() {
  return window['go']['main']['App']['PackGenProviders']();
}

export function PackGenSlots() {
  return window['go']['main']['App']['PackGenSlots']();
}

export function PackGenStatus() {
  return window['go']['main']['App']['PackGenStatus']();
}

export function PackGenStyles() {
  return window['go']['main']['App']['PackGenStyles']();
}

export function PickCompanionPack() {
  return window['go']['main']['App']['PickCompanionPack']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickPackGenBase() {
  return window['go']['main']['App']['PickPackGenBase']();
}

export function PinProject(arg1, arg2) {
  return window['go']['main']['App']['PinProject'](arg1, arg2);
}

export function PlanUsage() {
  return window['go']['main']['App']['PlanUsage']();
}

export function RemoveModel(arg1) {
  return window['go']['main']['App']['RemoveModel'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RenderProjectDoc(arg1, arg2) {
  return window['go']['main']['App']['RenderProjectDoc'](arg1, arg2);
}

export function SavePackGen() {
  return window['go']['main']['App']['SavePackGen']();
}

export function SelectCompanionPack(arg1) {
  return window['go']['main']['App']['SelectCompanionPack'](arg1);
}

export function SelectSession(arg1) {
  return window['go']['main']['App']['SelectSession'](arg1);
}

export function SessionStats(arg1) {
  return window['go']['main']['App']['SessionStats'](arg1);
}

export function SetCompanionKind(arg1) {
  return window['go']['main']['App']['SetCompanionKind'](arg1);
}

export function SetImagegenKey(arg1, arg2) {
  return window['go']['main']['App']['SetImagegenKey'](arg1, arg2);
}

export function SetKey(arg1, arg2) {
  return window['go']['main']['App']['SetKey'](arg1, arg2);
}

export function SetPackVariantFocus(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetPackVariantFocus'](arg1, arg2, arg3, arg4, arg5);
}

export function StartPackGen(arg1) {
  return window['go']['main']['App']['StartPackGen'](arg1);
}

export function SwapModel(arg1, arg2) {
  return window['go']['main']['App']['SwapModel'](arg1, arg2);
}

export function WSPort() {
  return window['go']['main']['App']['WSPort']();
}

export function WSToken() {
  return window['go']['main']['App']['WSToken']();
}
