// Package imagegen is a provider-agnostic client for hosted image generation
// and image editing APIs. It takes an input image, a prompt and a mode, and
// returns an image. It deliberately knows nothing about what the caller does
// with the result.
package imagegen

import (
	"context"
	"fmt"
	"sort"
	"sync"
)

// Mode selects the mechanism a request uses. Two exist because they are not
// interchangeable: img2img re-runs part of a denoise schedule from the input
// image and cannot reliably change a subject's pose, while an instruction edit
// takes a sentence and no denoise fraction at all.
type Mode string

const (
	// ModeImg2Img runs a strength-controlled denoise starting from Base.
	ModeImg2Img Mode = "img2img"
	// ModeEdit is instruction-conditioned and ignores Strength entirely.
	ModeEdit Mode = "edit"
)

// Request is one output image, produced from one input image and one prompt.
type Request struct {
	Mode Mode
	// Model is the provider-native id to run. Empty means the provider's
	// default.
	//
	// It belongs on the REQUEST, not on the provider struct, because providers
	// are stateless and shared. With only one model the two were
	// indistinguishable — and the model the UI let the user pick was silently
	// ignored, every run using the default regardless. A second model is what
	// made that visible.
	Model    string
	Base     []byte // the input image bytes
	BaseMIME string // MIME type of Base; sniffed when empty
	Prompt   string
	Negative string

	// Strength is meaningful only for ModeImg2Img. Instruction-edit models take
	// an instruction, not a denoise fraction, and ignore this field. It is kept
	// on the request so a future img2img provider is reachable without changing
	// the interface.
	Strength float64

	// Seed is generated by the caller and echoed back on the Result. Providers
	// do not reliably return one, so caller-side generation is the only scheme
	// that works uniformly.
	Seed int64

	// Portrait requests a portrait aspect bucket where the provider offers a
	// choice. Providers that do not are free to ignore it.
	Portrait bool
}

// Result is one generated image.
type Result struct {
	Image []byte
	MIME  string // sniffed from the returned bytes, never assumed
	Seed  int64  // echoed from Request
	Model string

	// FinishReason is "" on success. Anything else means the provider produced
	// bytes the caller must not use — a moderation flag, most commonly. It is a
	// field rather than an error because the bytes may still be worth showing
	// the user while refusing to keep them.
	FinishReason string

	// Billed reports whether the PROVIDER charged for this call, independent of
	// whether the caller got a usable image.
	//
	// It exists because the two are not the same and the caller cannot tell
	// them apart from the error alone. Once a submit returns 2xx the work is
	// done and paid for; everything that can still fail after that — the result
	// download exhausting its retries, a response carrying no images, a body
	// that will not decode — arrives as an ordinary error. Inferring "error
	// therefore free" under-reported spend on every one of those paths.
	Billed bool
}

// ErrorResult is the Result to return alongside an error once the provider has
// already been paid. Using it rather than a bare Result{} is what stops a
// post-submit failure from being reported as free.
func ErrorResult(model string, seed int64) Result {
	return Result{Model: model, Seed: seed, Billed: true}
}

// Model is one model a Provider can run.
type Model struct {
	ID    string // provider-native id, e.g. "fal-ai/nano-banana-2/edit"
	Label string
	Mode  Mode

	// Refusal records HOW this model declines a prompt. It matters because the
	// two mechanisms cost the user differently, and the UI has to be able to
	// say which one happened:
	//
	//   RefusalBlackImage  — HTTP 200 carrying an all-black frame. BILLED.
	//   RefusalPromptError — HTTP 422 before generating. Not billed.
	//   RefusalUnknown     — no mechanism the vendor documents.
	Refusal string

	// Note is shown beside the model in the picker. For a measured caveat, not
	// for marketing copy.
	Note string
}

// How a model refuses. Measured per model rather than assumed: two spikes over
// three base images found nano-banana-2 refused nothing in 10 attempts while
// flux-2 klein 4B returned a billed black frame on 3 of 18.
const (
	RefusalBlackImage  = "black_image"
	RefusalPromptError = "prompt_error"
	RefusalUnknown     = "unknown"
)

// Provider is one hosted image API. Implementations are stateless: the API key
// is passed per call so it can live in the OS keychain and be read at the last
// possible moment rather than held in a struct field.
type Provider interface {
	ID() string
	Models() []Model
	Generate(ctx context.Context, key string, r Request) (Result, error)
}

var (
	regMu    sync.RWMutex
	registry = map[string]Provider{}
)

// Register adds p to the package registry, normally from an init function.
// It panics on an empty or duplicate id: both are programmer errors, and a
// silent overwrite would surface as the wrong provider being called much later.
func Register(p Provider) {
	regMu.Lock()
	defer regMu.Unlock()
	id := p.ID()
	if id == "" {
		panic("imagegen: provider registered with an empty ID")
	}
	if _, dup := registry[id]; dup {
		panic(fmt.Sprintf("imagegen: provider %q registered twice", id))
	}
	registry[id] = p
}

// Lookup returns the registered provider with the given id.
func Lookup(id string) (Provider, bool) {
	regMu.RLock()
	defer regMu.RUnlock()
	p, ok := registry[id]
	return p, ok
}

// Providers returns every registered provider ordered by id, so a caller
// rendering a picker gets a stable list rather than Go's randomised map order.
func Providers() []Provider {
	regMu.RLock()
	defer regMu.RUnlock()
	out := make([]Provider, 0, len(registry))
	for _, p := range registry {
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID() < out[j].ID() })
	return out
}
